apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  type: NodePort
  selector:
    app: apache-web-solutions     # conecta este Service aos Pods do Deployment apache-deployment
  ports:
    - port: 8081                  # porta pela qual outros serviços DENTRO do cluster acessam
      targetPort: 80               # porta em que o container Apache realmente escuta
      nodePort: 30081              # porta exposta no NODE do cluster (faixa 30000-32767)
      protocol: TCP
