apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort                  # expõe o serviço fora do cluster (ideal para minikube/kind)
  selector:
    app: nginx-web-solutions      # conecta este Service aos Pods do Deployment nginx-deployment
  ports:
    - port: 8080                  # porta pela qual outros serviços DENTRO do cluster acessam
      targetPort: 80               # porta em que o container Nginx realmente escuta
      nodePort: 30080              # porta exposta no NODE do cluster (faixa 30000-32767)
      protocol: TCP
